# Per-family overrides for the built-in AI prompts, editable from
# /settings/ai_prompts so tuning them no longer needs a fork + redeploy.
#
# Every override is stored in one jsonb column and resolved at the point of use
# (`Assistant::Configurable#default_instructions` and the four provider
# `instructions` methods) as `family&.ai_prompt(key) || <hardcoded default>`.
# A blank value is deleted on save, so clearing a field *is* resetting it.
module Family::AiPromptable
  extend ActiveSupport::Concern

  # Overrides are sent to the provider on every call, so an unbounded value is a
  # cost problem, not just a storage one. Generous next to the ~4KB defaults.
  MAX_LENGTH = 20_000

  # Each key's stock text, lazily. Constructing a provider class with
  # `family: nil` is exactly what returns the hardcoded default, so no prompt
  # string is duplicated here.
  DEFAULTS = {
    chat_system: -> { Assistant::Configurable::STATIC_INSTRUCTIONS },
    categorizer_openai: -> { Provider::Openai::AutoCategorizer.new(nil).instructions },
    categorizer_anthropic: -> { Provider::Anthropic::AutoCategorizer.new(nil, model: "").instructions },
    merchant_openai: -> { Provider::Openai::AutoMerchantDetector.new(nil, model: "", transactions: [], user_merchants: []).instructions },
    merchant_anthropic: -> { Provider::Anthropic::AutoMerchantDetector.new(nil, model: "", transactions: [], user_merchants: []).instructions }
  }.freeze

  KEYS = DEFAULTS.keys.freeze

  # Attribute names generated by `store_accessor` below — the form fields and the
  # controller's permitted params.
  FIELDS = KEYS.map { |key| :"ai_prompt_#{key}" }.freeze

  included do
    store_accessor :ai_prompt_overrides, *KEYS, prefix: :ai_prompt

    # Assigned rather than mutated in place so the jsonb attribute is
    # unambiguously dirty when only blanks were submitted (a reset).
    before_save { self.ai_prompt_overrides = ai_prompt_overrides.compact_blank }

    validates *FIELDS,
      length: {
        maximum: MAX_LENGTH,
        message: ->(_object, _data) {
          I18n.t("errors.messages.too_long", count: MAX_LENGTH.to_fs(:delimited))
        }
      },
      allow_blank: true
  end

  # The family's override for `key`, or nil when it runs the default.
  def ai_prompt(key)
    ai_prompt_overrides[key.to_s].presence
  end

  def ai_prompt_default(key)
    DEFAULTS.fetch(key.to_sym).call
  end
end
