require "test_helper"

class AccountStatement::VectorStoreBridgeTest < ActiveSupport::TestCase
  include ActiveJob::TestHelper

  setup do
    @family = families(:dylan_family)
  end

  def build_statement(filename: "releve.pdf", account: nil)
    statement = @family.account_statements.build(
      account: account,
      filename: filename,
      content_type: "application/pdf",
      byte_size: 42,
      checksum: SecureRandom.hex(16),
      content_sha256: SecureRandom.hex(32),
      source: :manual_upload,
      upload_status: :stored,
      review_status: :unmatched,
      currency: "USD"
    )
    statement.original_file.attach(io: StringIO.new("%PDF-1.4 fake"), filename: filename, content_type: "application/pdf")
    statement
  end

  def stub_upload(file_id)
    VectorStore::Registry.stubs(:adapter).returns(
      stub(
        upload_file: VectorStore::Response.new(success?: true, data: { file_id: file_id }, error: nil)
      )
    )
    @family.update!(vector_store_id: "vs_test")
  end

  test "creating a statement enqueues its indexing" do
    statement = build_statement

    assert_enqueued_with(job: IndexAccountStatementJob) do
      statement.save!
    end

    # The id is generated by the insert, so the argument can only be checked
    # once the save has happened.
    assert_equal [ statement.id ], enqueued_jobs.last["arguments"]
  end

  test "indexing pushes the file into the document store with a linking key" do
    statement = build_statement
    statement.save!

    # Expected on the class, not on statement.family: index_in_vector_store!
    # locks the row, and the reload that comes with the lock resets the cached
    # association, so an expectation set on this instance would never be met.
    Family.any_instance.expects(:upload_document).with do |args|
      args[:filename] == "releve.pdf" &&
        args[:metadata]["account_statement_id"] == statement.id &&
        args[:metadata]["type"] == "account_statement"
    end.returns(FamilyDocument.new)

    assert statement.index_in_vector_store!
  end

  test "does not index the same statement twice" do
    statement = build_statement
    statement.save!

    @family.family_documents.create!(
      filename: "releve.pdf",
      content_type: "application/pdf",
      file_size: 42,
      provider_file_id: "file_1",
      status: "ready",
      metadata: { "account_statement_id" => statement.id }
    )

    assert statement.indexed_in_vector_store?
    assert_not statement.index_in_vector_store!, "a second index would duplicate the document"
  end

  # The existence check alone is check-then-write, and ProcessPdfJob runs the
  # same check on a different queue with no ordering between them: two workers
  # that both read "not indexed" both upload, leaving two documents for one
  # statement. Only the row lock serializes them, so its absence is the bug.
  # A real race cannot be reproduced in-process, so what is pinned is that the
  # lock is taken before the check.
  test "takes the statement row lock before deciding to index" do
    statement = build_statement
    statement.save!

    statement.expects(:with_lock).once

    statement.index_in_vector_store!
  end

  # The account link decides who may read the document back, so it lives in a
  # column rather than a jsonb key: metadata cannot be joined, indexed or
  # constrained, and the store itself is one family-wide index.
  test "an indexed statement lands with its owning account on the document" do
    account = accounts(:connected)
    statement = build_statement(account: account)
    statement.review_status = :linked
    statement.save!

    stub_upload("file_acct")

    statement.index_in_vector_store!
    document = @family.family_documents.find_by(provider_file_id: "file_acct")

    assert_equal account.id, document.account_id
    assert_includes @family.family_documents.readable_by(users(:family_admin)), document
    assert_not_includes @family.family_documents.readable_by(users(:family_member)), document
  end

  # Indexing runs on upload, which is often before anyone has said which account
  # the statement belongs to. The document therefore starts family-wide and only
  # the link narrows it, so the link has to reach the document too.
  test "linking a statement narrows its indexed document to the account" do
    statement = build_statement
    statement.save!

    stub_upload("file_link")
    statement.index_in_vector_store!
    document = @family.family_documents.find_by(provider_file_id: "file_link")

    assert_nil document.account_id
    assert_includes @family.family_documents.readable_by(users(:family_member)), document

    statement.link_to_account!(accounts(:connected))

    assert_equal accounts(:connected).id, document.reload.account_id
    assert_equal accounts(:connected).id, document.metadata["account_id"]
    assert_not_includes @family.family_documents.readable_by(users(:family_member)), document
  end

  # The Link button is not the only writer. AccountStatementsController#update
  # re-adds :account_id outside strong params and links a statement too, and it
  # left the indexed copy at its old account, readable by every statement
  # manager. Keyed on the attribute now, so any writer is covered.
  test "linking through a plain update narrows the document too" do
    statement = build_statement
    statement.save!

    stub_upload("file_plain_update")
    statement.index_in_vector_store!
    document = @family.family_documents.find_by(provider_file_id: "file_plain_update")

    assert_nil document.account_id

    statement.update!(account: accounts(:connected))

    assert_equal accounts(:connected).id, document.reload.account_id
    assert_not_includes @family.family_documents.readable_by(users(:family_member)), document
  end

  # The indexed copy is a separate row and a provider-side file, so deleting the
  # statement left its text searchable by everyone the document was readable by.
  test "deleting a statement removes its indexed copy" do
    statement = build_statement
    statement.save!

    stub_upload("file_destroy")
    statement.index_in_vector_store!
    document = @family.family_documents.find_by(provider_file_id: "file_destroy")

    assert_not_nil document

    Family.any_instance.expects(:remove_document).with(document).once

    statement.destroy!
  end

  # add_reference ... foreign_key: true defaults to NO ACTION, so destroying an
  # account that had an indexed statement raised InvalidForeignKey and rolled the
  # whole destroy back. The link is nullable: losing the account makes the
  # document family-wide again, which is what the column already means.
  test "destroying an account releases its documents instead of blocking" do
    account = @family.accounts.create!(
      accountable: Depository.new, name: "Compte a supprimer", balance: 10, currency: "USD"
    )
    document = @family.family_documents.create!(
      filename: "releve.pdf", content_type: "application/pdf", file_size: 42,
      provider_file_id: "file_fk", status: "ready", account: account
    )

    assert_nothing_raised { account.destroy! }
    assert_nil document.reload.account_id
  end

  test "unlinking a statement releases its indexed document from the account" do
    statement = build_statement(account: accounts(:connected))
    statement.review_status = :linked
    statement.save!

    stub_upload("file_unlink")
    statement.index_in_vector_store!
    document = @family.family_documents.find_by(provider_file_id: "file_unlink")

    assert_equal accounts(:connected).id, document.account_id

    AccountStatement::AccountMatcher.any_instance.stubs(:best_match).returns(nil)
    statement.unlink!

    assert_nil document.reload.account_id
    assert_not document.metadata.key?("account_id"), "a released document must not keep the account it left"
    assert_includes @family.family_documents.readable_by(users(:family_member)), document
  end

  # An unlinked statement is gated on statement_manager? by
  # AccountStatement#viewable_by?, so "no account" must not read as "everyone":
  # a guest reaching the vault through search would otherwise get its text.
  test "an unmatched statement's document stays out of a guest's reach" do
    statement = build_statement
    statement.save!

    stub_upload("file_guest")
    statement.index_in_vector_store!
    document = @family.family_documents.find_by(provider_file_id: "file_guest")

    guest = users(:family_member)
    guest.update!(role: :guest)

    assert_nil document.account_id
    assert_not_includes @family.family_documents.readable_by(guest), document
    assert_includes @family.family_documents.readable_by(users(:family_admin)), document
  end

  test "a document that is not a statement stays family-wide for a guest" do
    guest = users(:family_member)
    guest.update!(role: :guest)

    document = @family.family_documents.create!(
      filename: "contrat.pdf",
      content_type: "application/pdf",
      status: "ready",
      metadata: { "type" => "contract" }
    )

    assert_includes @family.family_documents.readable_by(guest), document
  end

  # readable_by evaluates the account's own sharing, so a document pointed at
  # another family's account would be judged against the wrong owner entirely.
  test "a document cannot name an account from another family" do
    foreign_account = Account.create!(
      family: families(:empty),
      owner: users(:empty),
      name: "Another family's account",
      balance: 0,
      currency: "USD",
      accountable: Depository.new
    )

    document = @family.family_documents.new(
      filename: "etranger.pdf",
      content_type: "application/pdf",
      status: "ready",
      account: foreign_account
    )

    assert_not document.valid?
    assert_includes document.errors.attribute_names, :account
  end

  # remove_document reports failure by returning false, not by raising, and on
  # false it leaves the row in place. Silence there means the deleted
  # statement's text is still searchable, which is what this callback exists to
  # prevent, so the failure has to reach support.
  test "records a failed removal instead of leaving it silent" do
    statement = build_statement
    statement.save!

    stub_upload("file_remove_fail")
    statement.index_in_vector_store!

    VectorStore::Registry.stubs(:adapter).returns(
      stub(remove_file: VectorStore::Response.new(success?: false, data: nil,
                                                 error: VectorStore::Error.new("provider down")))
    )

    DebugLogEntry.expects(:capture).with do |args|
      args[:category] == "documents" && args[:message].match?(/could not be removed/)
    end.once

    statement.destroy!

    assert @family.family_documents.exists?(provider_file_id: "file_remove_fail"),
           "the row must survive a failed provider removal rather than being dropped silently"
  end

  # index_in_vector_store! answers false for "nothing attached" too, so the
  # refusal log reported a missing file as a provider saying no.
  test "does not report a missing attachment as a provider refusal" do
    statement = build_statement
    statement.save!
    statement.original_file.purge

    stub_upload("file_never_used")

    DebugLogEntry.expects(:capture).never

    IndexAccountStatementJob.new.perform(statement.id)
  end

  test "an install with no vector store still accepts the upload" do
    statement = build_statement

    assert_nothing_raised { statement.save! }
    assert statement.persisted?
    assert_not statement.index_in_vector_store!, "no adapter means no indexing, not a failed upload"
  end

  test "the job never lets an indexing failure escape" do
    statement = build_statement
    statement.save!

    AccountStatement.any_instance.stubs(:index_in_vector_store!).raises(StandardError, "boom")

    assert_nothing_raised { IndexAccountStatementJob.new.perform(statement.id) }
  end

  test "the job tolerates a statement deleted before it runs" do
    assert_nothing_raised { IndexAccountStatementJob.new.perform(SecureRandom.uuid) }
  end
end
