module SnaptradeItem::Provided
  extend ActiveSupport::Concern

  included do
    before_destroy :delete_snaptrade_user
  end

  def snaptrade_provider
    return nil unless credentials_configured?

    Provider::Snaptrade.new(
      client_id: client_id,
      consumer_key: consumer_key
    )
  end

  # Clean up SnapTrade user when item is destroyed
  def delete_snaptrade_user
    return unless user_registered?

    # Only delete users that Sure itself registered (app-generated `family_<id>_<ts>`
    # IDs). Personal-key users supply a pre-provisioned SnapTrade user from their own
    # dashboard; deleting that via the API would destroy their real SnapTrade user
    # and every brokerage connection attached to it.
    unless app_generated_user_id?(snaptrade_user_id)
      Rails.logger.info "SnapTrade: Skipping API deletion of externally-provisioned user for family #{family_id}"
      return
    end

    provider = snaptrade_provider
    return unless provider

    provider.delete_user(user_id: snaptrade_user_id)
  rescue => e
    # Log but don't block deletion - user may not exist or credentials may be invalid
    capture_snaptrade_debug(
      level: "warn",
      message: "Failed to delete SnapTrade user",
      metadata: { app_generated: app_generated_user_id?(snaptrade_user_id), error_class: e.class.name, error_message: e.message }
    )
  end

  # True when the user ID was generated by Sure during registration (vs. a
  # pre-provisioned personal-key user supplied by the customer).
  def app_generated_user_id?(user_id)
    user_id.to_s.start_with?("family_#{family_id}_")
  end

  # User ID and secret for SnapTrade API calls
  def snaptrade_credentials
    return nil unless snaptrade_user_id.present? && snaptrade_user_secret.present?

    {
      user_id: snaptrade_user_id,
      user_secret: snaptrade_user_secret
    }
  end

  # Check if user is registered with SnapTrade
  def user_registered?
    snaptrade_user_id.present? && snaptrade_user_secret.present?
  end

  # Register user with SnapTrade if not already registered.
  # Returns true if registration succeeded or already registered.
  # If a Sure-registered user no longer exists, clears the stale credentials and
  # re-registers. Personal-key (externally provisioned) credentials are never
  # cleared or re-registered; failed verification surfaces actionable guidance.
  def ensure_user_registered!
    # If we think we're registered, verify the user still exists. This covers both
    # auto-registered users and pre-provisioned credentials supplied manually for a
    # personal key.
    if user_registered?
      return true if verify_user_exists?

      if app_generated_user_id?(snaptrade_user_id)
        # Sure-registered user no longer exists upstream (e.g. deleted) — clear the
        # stale credentials so we re-register with a fresh ID below. Without this,
        # every call would re-verify the same dead user instead of recovering.
        capture_snaptrade_debug(
          level: "warn",
          message: "Sure-registered SnapTrade user no longer exists; clearing credentials and re-registering",
          metadata: { app_generated: true }
        )
        update!(snaptrade_user_id: nil, snaptrade_user_secret: nil)
      else
        # Externally-provisioned personal-key user. registerUser can't mint a
        # replacement, and clearing would discard the user's only credentials, so
        # surface actionable guidance instead of attempting a doomed re-register.
        capture_snaptrade_debug(
          level: "warn",
          message: "Personal-key SnapTrade user failed verification",
          metadata: { app_generated: false }
        )
        raise SnaptradeItem::RegistrationError, I18n.t("snaptrade_item.errors.personal_key_registration_unavailable")
      end
    end

    provider = snaptrade_provider
    raise StandardError, "SnapTrade provider not configured" unless provider

    # Use family ID with current timestamp to ensure uniqueness (avoids conflicts from previous deletions)
    unique_user_id = "family_#{family_id}_#{Time.current.to_i}"

    result = provider.register_user(unique_user_id)

    update!(
      snaptrade_user_id: result[:user_id],
      snaptrade_user_secret: result[:user_secret]
    )

    true
  rescue Provider::Snaptrade::PersonalKeyError
    # Personal keys can't call registerUser. Surface an actionable message so the
    # user knows to paste their pre-provisioned User ID and User Secret instead.
    capture_snaptrade_debug(
      level: "error",
      message: "registerUser is not available for personal SnapTrade keys"
    )
    raise SnaptradeItem::RegistrationError, I18n.t("snaptrade_item.errors.personal_key_registration_unavailable")
  rescue Provider::Snaptrade::ApiError => e
    # Capture status code but never the response body (may contain credentials).
    capture_snaptrade_debug(
      level: "error",
      message: "SnapTrade user registration failed",
      metadata: { error_class: e.class.name, status_code: e.try(:status_code) }
    )

    # Check if user already exists (shouldn't happen with timestamp suffix, but handle gracefully)
    if e.message.include?("already registered") || e.message.include?("already exists")
      raise StandardError, "User registration conflict. Please try again."
    end

    raise
  end

  # Verify that the stored user actually exists in SnapTrade.
  # Returns true if it exists, false if it is definitively missing (401/403/404).
  # Transient failures (429, 5xx, network) are re-raised so callers don't mistake
  # them for a missing user and wipe/re-register valid credentials.
  def verify_user_exists?
    return false unless snaptrade_user_id.present?

    provider = snaptrade_provider
    return false unless provider

    # Listing connections returns 401/403 if the user no longer exists.
    provider.list_connections(
      user_id: snaptrade_user_id,
      user_secret: snaptrade_user_secret
    )
    true
  rescue Provider::Snaptrade::AuthenticationError
    # Definitive: the credentials were rejected — the user is gone.
    false
  rescue Provider::Snaptrade::ApiError => e
    # Only an explicit 404 means "missing user". Anything else (429, 5xx, network)
    # is transient — re-raise so stored credentials are preserved.
    raise unless e.try(:status_code) == 404

    false
  end

  # Get the connection portal URL for linking brokerages
  def connection_portal_url(redirect_url:, broker: nil)
    raise StandardError, "User not registered with SnapTrade" unless user_registered?

    provider = snaptrade_provider
    raise StandardError, "SnapTrade provider not configured" unless provider

    provider.get_connection_url(
      user_id: snaptrade_user_id,
      user_secret: snaptrade_user_secret,
      redirect_url: redirect_url,
      broker: broker
    )
  end

  # Fetch all brokerage connections from SnapTrade API
  # Returns array of connection objects
  def fetch_connections
    return [] unless credentials_configured? && user_registered?

    provider = snaptrade_provider
    creds = snaptrade_credentials
    provider.list_connections(user_id: creds[:user_id], user_secret: creds[:user_secret])
  rescue Provider::Snaptrade::ApiError => e
    Rails.logger.error "SnaptradeItem #{id} - Failed to list connections: #{e.message}"
    raise
  end

  # List all SnapTrade users registered under this client ID
  def list_all_users
    return [] unless credentials_configured?

    snaptrade_provider.list_users
  rescue Provider::Snaptrade::ApiError => e
    Rails.logger.error "SnaptradeItem #{id} - Failed to list users: #{e.message}"
    []
  end

  # Find orphaned SnapTrade users (registered but not current user)
  def orphaned_users
    return [] unless credentials_configured? && user_registered?

    all_users = list_all_users
    all_users.select { |uid| uid != snaptrade_user_id && app_generated_user_id?(uid) }
  end

  # Delete an orphaned SnapTrade user and all their connections
  def delete_orphaned_user(user_id)
    return false unless credentials_configured?
    return false if user_id == snaptrade_user_id # Don't delete current user
    return false unless app_generated_user_id?(user_id)

    snaptrade_provider.delete_user(user_id: user_id)
    true
  rescue Provider::Snaptrade::ApiError => e
    Rails.logger.error "SnaptradeItem #{id} - Failed to delete orphaned user: #{e.message}"
    false
  end

  private

    # Capture support-relevant SnapTrade diagnostics without leaking the provider
    # user ID — for personal keys that ID is the customer's real dashboard user.
    def capture_snaptrade_debug(level:, message:, metadata: {})
      DebugLogEntry.capture(
        category: "provider_sync_error",
        level: level,
        message: message,
        source: "SnaptradeItem",
        provider_key: "snaptrade",
        family: family,
        metadata: { snaptrade_item_id: id }.merge(metadata)
      )
    end
end
