---
fr:
  family_exports:
    access_denied: Accès refusé
    create:
      success: L'exportation a commencé. Vous pourrez bientôt la télécharger.
    delete_confirmation: Êtes-vous sûr de vouloir supprimer cette exportation ? Cette
      action est irréversible.
    delete_failed_confirmation: Êtes-vous sûr de vouloir supprimer cette exportation
      qui a échoué ?
    destroy:
      success: Exportation supprimée avec succès
    export_not_ready: Exportation non prête pour le téléchargement
    exporting: Exporte...
    index:
      new: Nouvelle exportation
      title: Exportations
    new:
      accounts_and_balances: Tous les comptes et soldes
      cancel: Annuler
      categories_tags_rules: Catégories, balises et règles
      dialog_subtitle: Téléchargez toutes vos données financières
      dialog_title: Exportez vos données
      export_data: Exporter des données
      investment_trades: Métiers d'investissement
      note_description: Cette exportation inclut toutes vos données, mais seules certaines
        d'entre elles peuvent être réimportées via la fonction d'importation CSV.
        Nous prenons en charge les importations de comptes, de transactions (avec
        catégorie et balises) et commerciales. Les autres données du compte ne peuvent
        pas être importées et sont uniquement destinées à vos dossiers.
      note_label: Remarque
      transaction_history: Historique des transactions
      whats_included: 'Ce qui est inclus :'
    table:
      empty: Aucune exportation pour l'instant.
      header:
        actions: Actions
        date: Date
        filename: Nom de fichier
        status: Statut
      row:
        actions:
          delete: Supprimer
          download: Télécharger
        status:
          complete: Terminé
          failed: Échoué
          in_progress: En cours
      title: Exportations
