---
ru:
  activerecord:
    attributes:
      doorkeeper/application:
        name: Название
        redirect_uri: URI перенаправления
    errors:
      models:
        doorkeeper/application:
          attributes:
            redirect_uri:
              forbidden_uri: запрещён сервером.
              fragment_present: не может содержать фрагмент.
              invalid_uri: должен быть допустимым URI.
              relative_uri: должен быть абсолютным URI.
              secured_uri: должен быть HTTPS/SSL URI.
              unspecified_scheme: должен указать схему.
            scopes:
              not_match_configured: не соответствует настроенному на сервере.
  doorkeeper:
    applications:
      buttons:
        authorize: Авторизовать
        cancel: Отмена
        destroy: Удалить
        edit: Редактировать
        submit: Отправить
      confirmations:
        destroy: Вы уверены?
      edit:
        title: Редактировать приложение
      form:
        error: Упс! Проверьте форму на наличие ошибок
      help:
        blank_redirect_uri: Оставьте пустым, если вы настроили своего провайдера на
          использование Client Credentials, Resource Owner Password Credentials или
          любого другого типа гранта, который не требует URI перенаправления.
        confidential: Приложение будет использоваться там, где секрет клиента может
          быть сохранён конфиденциально. Нативные мобильные приложения и одностраничные
          приложения считаются неконфиденциальными.
        redirect_uri: Используйте одну строку на каждый URI
        scopes: Разделяйте области пробелами. Оставьте пустым для использования областей
          по умолчанию.
      index:
        actions: Действия
        callback_url: URL обратного вызова
        confidential: Конфиденциально?
        confidentiality:
          'no': Нет
          'yes': Да
        name: Название
        new: Новое приложение
        title: Ваши приложения
      new:
        title: Новое приложение
      show:
        actions: Действия
        application_id: UID
        callback_urls: URL-ы обратного вызова
        confidential: Конфиденциально
        not_defined: Не определено
        scopes: Области
        secret: Секрет
        secret_hashed: Хэшированный секрет
        title: 'Приложение: %{name}'
    authorizations:
      buttons:
        authorize: Авторизовать
        deny: Отклонить
      error:
        go_back: Вернуться назад
        title: Произошла ошибка
      form_post:
        title: Отправьте эту форму
      new:
        able_to: Это приложение сможет
        prompt: Авторизовать %{client_name} для использования вашего счёта?
        title: Требуется авторизация
      show:
        authorization_code_label: 'Код авторизации:'
        copy_instructions: Скопируйте этот код и вставьте его в приложение.
        title: Код авторизации
    authorized_applications:
      buttons:
        revoke: Отозвать
      confirmations:
        revoke: Вы уверены?
      index:
        application: Приложение
        created_at: Создано
        date_format: "%d.%m.%Y %H:%M:%S"
        title: Ваши авторизованные приложения
    errors:
      messages:
        access_denied: Владелец ресурса или сервер авторизации отклонил запрос.
        admin_authenticator_not_configured: Доступ к админ-панели запрещён из-за ненастроенного
          Doorkeeper.configure.admin_authenticator.
        credential_flow_not_configured: Поток Resource Owner Password Credentials
          не настроен из-за ненастроенного Doorkeeper.configure.resource_owner_from_credentials.
        forbidden_token:
          missing_scope: Доступ к этому ресурсу требует области "%{oauth_scopes}".
        invalid_client: Аутентификация клиента не удалась из-за неизвестного клиента,
          отсутствия аутентификации клиента или неподдерживаемого метода аутентификации.
        invalid_code_challenge_method:
          one: "Параметр code_challenge_method должен быть %{challenge_methods}."
          few: "Параметр code_challenge_method должен быть одним из %{challenge_methods}."
          many: "Параметр code_challenge_method должен быть одним из %{challenge_methods}."
          other: "Параметр code_challenge_method должен быть одним из %{challenge_methods}."
          zero: Сервер авторизации не поддерживает PKCE, так как нет допустимых значений
            code_challenge_method.
        invalid_grant: Предоставленный грант авторизации недействителен, истёк, отозван,
          не соответствует URI перенаправления, использованному в запросе авторизации,
          или был выдан другому клиенту.
        invalid_redirect_uri: Запрашиваемый URI перенаправления некорректен или не
          соответствует URI перенаправления клиента.
        invalid_request:
          invalid_code_challenge: Требуется код вызова.
          missing_param: 'Отсутствует обязательный параметр: %{value}.'
          request_not_authorized: Запрос должен быть авторизован. Отсутствует или
            недействителен обязательный параметр для авторизации запроса.
          unknown: Запрос отсутствует обязательный параметр, включает неподдерживаемое
            значение параметра или иным образом некорректен.
        invalid_scope: Запрашиваемая область недействительна, неизвестна или некорректна.
        invalid_token:
          expired: Токен доступа истёк
          revoked: Токен доступа был отозван
          unknown: Токен доступа недействителен
        resource_owner_authenticator_not_configured: Поиск владельца ресурса не удался
          из-за ненастроенного Doorkeeper.configure.resource_owner_authenticator.
        revoke:
          unauthorized: Вы не авторизованы для отзыва этого токена
        server_error: Сервер авторизации столкнулся с неожиданной проблемой, которая
          помешала ему выполнить запрос.
        temporarily_unavailable: Сервер авторизации временно не может обработать запрос
          из-за перегрузки или обслуживания сервера.
        unauthorized_client: Клиент не авторизован для выполнения этого запроса с
          использованием этого метода.
        unsupported_grant_type: Тип гранта авторизации не поддерживается сервером
          авторизации.
        unsupported_response_mode: Сервер авторизации не поддерживает этот режим ответа.
        unsupported_response_type: Сервер авторизации не поддерживает этот тип ответа.
    flash:
      applications:
        create:
          notice: Приложение создано.
        destroy:
          notice: Приложение удалено.
        update:
          notice: Приложение обновлено.
      authorized_applications:
        destroy:
          notice: Приложение отозвано.
    layouts:
      admin:
        nav:
          applications: Приложения
          home: Главная
          oauth2_provider: Провайдер OAuth2
        title: Doorkeeper
      application:
        title: Требуется авторизация OAuth
    pre_authorization:
      status: Предварительная авторизация
