# Every legacy source column is named explicitly. Additions must be reviewed,
# classified and covered by migration tests before they can be copied.
class Provider::AccountData::MigrationManifestCatalog
  TABLES = {
    "akahu_accounts" => {
      identity: %w[id account_id akahu_item_id],
      attributes: %w[account_status account_type available_balance balance_limit created_at currency current_balance name sync_start_date updated_at],
      metadata: %w[institution_metadata provider],
      sensitive_data: %w[formatted_account],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "akahu_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[app_token user_token],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "binance_accounts" => {
      identity: %w[id binance_item_id],
      attributes: %w[account_type created_at currency current_balance name updated_at],
      metadata: %w[extra institution_metadata],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "binance_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[api_key api_secret],
      metadata: %w[institution_color institution_domain institution_name institution_url],
      payloads: %w[raw_payload],
    },
    "brex_accounts" => {
      identity: %w[id account_id brex_item_id],
      attributes: %w[account_kind account_limit account_status account_type available_balance created_at currency current_balance name updated_at],
      metadata: %w[institution_metadata provider],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "brex_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[token],
      settings: %w[base_url],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "coinbase_accounts" => {
      identity: %w[id account_id coinbase_item_id],
      attributes: %w[account_status account_type created_at currency current_balance name updated_at],
      metadata: %w[institution_metadata provider],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "coinbase_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[api_key api_secret],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "coinstats_accounts" => {
      identity: %w[id account_id coinstats_item_id wallet_address],
      attributes: %w[account_status account_type created_at currency current_balance name updated_at],
      metadata: %w[institution_metadata provider],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "coinstats_items" => {
      identity: %w[id exchange_connection_id exchange_portfolio_id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[api_key],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "enable_banking_accounts" => {
      identity: %w[id account_id enable_banking_item_id identification_hashes uid],
      attributes: %w[account_status account_type created_at credit_limit currency current_balance name updated_at],
      settings: %w[treat_balance_as_available_credit],
      metadata: %w[institution_metadata product provider],
      sensitive_data: %w[iban],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "enable_banking_items" => {
      identity: %w[id aspsp_id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[application_id authorization_id client_certificate session_id],
      settings: %w[aspsp_auth_approach aspsp_maximum_consent_validity aspsp_psu_types aspsp_required_psu_headers country_code psu_type],
      metadata: %w[aspsp_name institution_color institution_domain institution_id institution_name institution_url],
      checkpoints: %w[session_expires_at],
      sensitive_data: %w[last_psu_ip],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "ibkr_accounts" => {
      identity: %w[id ibkr_account_id ibkr_item_id],
      attributes: %w[cash_balance created_at currency current_balance name updated_at],
      metadata: %w[institution_metadata],
      checkpoints: %w[last_activities_sync last_holdings_sync report_date],
      payloads: %w[raw_activities_payload raw_cash_report_payload raw_equity_summary_payload raw_holdings_payload],
    },
    "ibkr_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status updated_at],
      credentials: %w[query_id token],
      payloads: %w[raw_payload],
    },
    "indexa_capital_accounts" => {
      identity: %w[id indexa_capital_account_id indexa_capital_authorization_id indexa_capital_item_id],
      attributes: %w[account_status account_type cash_balance created_at currency current_balance name sync_start_date updated_at],
      metadata: %w[institution_metadata provider],
      checkpoints: %w[activities_fetch_pending last_activities_sync last_holdings_sync],
      sensitive_data: %w[account_number],
      payloads: %w[raw_activities_payload raw_holdings_payload raw_payload],
    },
    "indexa_capital_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[api_token document password username],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "kraken_accounts" => {
      identity: %w[id account_id kraken_item_id],
      attributes: %w[account_type created_at currency current_balance name updated_at],
      metadata: %w[extra institution_metadata],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "kraken_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[api_key api_secret],
      metadata: %w[institution_color institution_domain institution_name institution_url],
      checkpoints: %w[last_nonce],
      payloads: %w[raw_payload],
    },
    "lunchflow_accounts" => {
      identity: %w[id account_id lunchflow_item_id],
      attributes: %w[account_status account_type created_at currency current_balance name updated_at],
      settings: %w[holdings_supported],
      metadata: %w[institution_metadata provider],
      payloads: %w[raw_holdings_payload raw_payload raw_transactions_payload],
    },
    "lunchflow_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[api_key],
      settings: %w[base_url],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "mercury_accounts" => {
      identity: %w[id account_id mercury_item_id],
      attributes: %w[account_status account_type created_at currency current_balance name updated_at],
      metadata: %w[institution_metadata provider],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "mercury_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[token],
      settings: %w[base_url],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "monobank_accounts" => {
      identity: %w[id account_id monobank_item_id],
      attributes: %w[account_kind account_status account_type created_at credit_limit currency current_balance name sync_start_date updated_at],
      settings: %w[ignored],
      metadata: %w[institution_metadata provider],
      checkpoints: %w[history_synced_from statement_synced_through],
      sensitive_data: %w[iban masked_pan],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "monobank_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[access_token],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "onchain_wallet_accounts" => {
      identity: %w[id chain contract_address onchain_wallet_item_id wallet_address],
      attributes: %w[asset_kind created_at currency current_balance decimals name quantity symbol updated_at],
      metadata: %w[extra],
      checkpoints: %w[content_hash],
      payloads: %w[raw_movements_payload raw_payload],
    },
    "onchain_wallet_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[etherscan_api_key],
      metadata: %w[institution_color institution_domain institution_name institution_url],
    },
    "plaid_accounts" => {
      identity: %w[id plaid_id plaid_item_id],
      attributes: %w[available_balance created_at currency current_balance name plaid_subtype plaid_type updated_at],
      sensitive_data: %w[mask],
      payloads: %w[raw_holdings_payload raw_liabilities_payload raw_payload raw_transactions_payload],
    },
    "plaid_items" => {
      identity: %w[id family_id plaid_id],
      attributes: %w[created_at name scheduled_for_deletion status updated_at],
      credentials: %w[access_token],
      settings: %w[available_products billed_products plaid_region],
      metadata: %w[institution_color institution_id institution_url],
      checkpoints: %w[next_cursor],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "questrade_accounts" => {
      identity: %w[id questrade_account_id questrade_authorization_id questrade_item_id],
      attributes: %w[account_status account_type cash_balance created_at currency current_balance name sync_start_date updated_at],
      metadata: %w[institution_metadata provider],
      checkpoints: %w[activities_fetch_pending activities_fetch_revision activities_fetch_due_at last_activities_sync last_holdings_sync],
      sensitive_data: %w[account_number],
      payloads: %w[activities_fetch_request raw_activities_payload raw_balances_payload raw_holdings_payload raw_payload],
    },
    "questrade_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[refresh_token],
      settings: %w[api_server],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "redbark_accounts" => {
      identity: %w[id connection_id redbark_account_id redbark_item_id],
      attributes: %w[account_status account_type created_at currency current_balance name sync_start_date updated_at],
      settings: %w[ignored],
      metadata: %w[institution_metadata provider],
      sensitive_data: %w[account_number],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "redbark_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[api_key],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "simplefin_accounts" => {
      identity: %w[id account_id simplefin_item_id],
      attributes: %w[account_subtype account_type available_balance balance_date created_at currency current_balance name updated_at],
      metadata: %w[extra org_data],
      payloads: %w[raw_holdings_payload raw_payload raw_transactions_payload],
    },
      "simplefin_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[access_url],
        metadata: %w[credential_revision institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "snaptrade_accounts" => {
      identity: %w[id snaptrade_account_id snaptrade_authorization_id snaptrade_item_id],
      attributes: %w[account_status account_type cash_balance created_at currency current_balance name sync_start_date updated_at],
      metadata: %w[brokerage_name institution_metadata provider],
      checkpoints: %w[activities_fetch_pending last_activities_sync last_holdings_sync],
      sensitive_data: %w[account_number],
      payloads: %w[raw_activities_payload raw_balances_payload raw_holdings_payload raw_payload raw_transactions_payload],
    },
    "snaptrade_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[client_id consumer_key oauth_access_token oauth_refresh_token snaptrade_user_id snaptrade_user_secret],
      settings: %w[oauth_scope oauth_token_type],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      checkpoints: %w[last_synced_at oauth_token_expires_at],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "sophtron_accounts" => {
      identity: %w[id account_id customer_id member_id sophtron_item_id],
      attributes: %w[account_status account_sub_type account_type available_balance balance created_at currency name updated_at],
      settings: %w[manual_sync],
      metadata: %w[institution_metadata],
      checkpoints: %w[last_updated],
      sensitive_data: %w[account_number_mask],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "sophtron_items" => {
      identity: %w[id customer_id family_id user_institution_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[access_key user_id],
      settings: %w[base_url manual_sync],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      checkpoints: %w[current_job_id current_job_sophtron_account_id job_status],
      sensitive_data: %w[customer_name last_connection_error],
      payloads: %w[raw_customer_payload raw_institution_payload raw_job_payload raw_payload],
    },
    "trade_republic_accounts" => {
      identity: %w[id trade_republic_account_id trade_republic_item_id],
      attributes: %w[account_type cash_balance created_at currency current_balance kind name updated_at],
      checkpoints: %w[holdings_snapshot_complete last_positions_sync],
      payloads: %w[raw_positions_payload raw_timeline_payload],
    },
    "trade_republic_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at currency name pending_account_setup scheduled_for_deletion status updated_at],
      credentials: %w[pending_login_state phone_number session_blob],
      checkpoints: %w[newest_event_id],
    },
    "trading212_accounts" => {
      identity: %w[id trading212_account_id trading212_item_id],
      attributes: %w[account_type cash_balance created_at currency current_balance name updated_at],
      checkpoints: %w[last_orders_sync last_positions_sync],
      payloads: %w[raw_dividends_payload raw_orders_payload raw_positions_payload raw_transactions_payload],
    },
    "trading212_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at currency name pending_account_setup scheduled_for_deletion status updated_at],
      credentials: %w[api_key api_secret],
      settings: %w[environment],
      payloads: %w[raw_instruments_payload],
    },
    "up_accounts" => {
      identity: %w[id account_id up_item_id],
      attributes: %w[account_status account_type created_at currency current_balance name sync_start_date updated_at],
      settings: %w[ignored ownership_type],
      metadata: %w[institution_metadata provider],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "up_items" => {
      identity: %w[id family_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[access_token],
      metadata: %w[institution_color institution_domain institution_id institution_name institution_url],
      payloads: %w[raw_institution_payload raw_payload],
    },
    "wise_accounts" => {
      identity: %w[id balance_id wise_item_id],
      attributes: %w[created_at currency current_balance name reserved_balance updated_at],
      payloads: %w[raw_payload raw_transactions_payload],
    },
    "wise_items" => {
      identity: %w[id family_id profile_id],
      attributes: %w[created_at name pending_account_setup scheduled_for_deletion status sync_start_date updated_at],
      credentials: %w[sca_private_key token],
      settings: %w[import_all_history profile_type],
      payloads: %w[raw_payload],
    },
  }.transform_values { |buckets| buckets.transform_values { |fields| fields.map(&:freeze).freeze }.freeze }.freeze
end
