
apiVersion: batch/v1
kind: Job
metadata:
  name: RELEASE-NAME-sure-migrate
  labels:
    app.kubernetes.io/name: sure
    helm.sh/chart: sure-0.6.7-alpha
    app.kubernetes.io/version: "0.6.7-alpha"
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
  annotations:
    # Run migrations after all chart resources (including CNPG Cluster/Services) are created
    # so the DB can actually come up before we connect and run db:prepare.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sure
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: migrate
          image: ghcr.io/we-promise/sure:0.6.6
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -lc
          args:
            - |
              
              DB_HOST=$(echo "$DATABASE_URL" | sed 's/.*@//; s/:.*//')
              until pg_isready -h "$DB_HOST" -p 5432; do echo "Waiting for DB..."; sleep 5; done
              echo "Preparing database (db:prepare)" && \
              DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rake db:prepare
              
          env:
            - name: RAILS_ENV
              value: "production"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-sure-app
                  key: SECRET_KEY_BASE
            - name: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-sure-app
                  key: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
            - name: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-sure-app
                  key: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
            - name: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-sure-app
                  key: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-sure-db-app
                  key: password
            - name: DATABASE_URL
              value: "postgresql://sure:$(DB_PASSWORD)@sure-db-rw.NAMESPACE.svc.cluster.local:5432/sure?sslmode=prefer"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-sure-app
                  key: redis-password
            - name: REDIS_URL
              value: "redis://default:$(REDIS_PASSWORD)@RELEASE-NAME-sure-redis-master.NAMESPACE.svc.cluster.local:6379/0"
            - name: AI_DEBUG_MODE
              value: ""
            - name: ONBOARDING_STATE
              value: "open"
            - name: SELF_HOSTED
              value: "true"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
          resources:
            {}
  ttlSecondsAfterFinished: 600
